name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Tests et Analyse de Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Nécessaire pour SonarCloud
        # Permet de pousser les modifications automatiques
        persist-credentials: false

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug
        tools: phpunit, phpcs, php-cs-fixer

    - name: Lint PHP
      run: php -l api.php

    - name: Vérification du style de code PHP
      id: phpcs
      continue-on-error: true
      run: phpcs --standard=PSR2 api.php

    - name: Correction automatique du style PHP
      if: steps.phpcs.outcome == 'failure'
      run: |
        php-cs-fixer fix api.php --rules=@PSR2
        
        # Configurer git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Vérifier s'il y a des modifications
        if [[ `git status --porcelain` ]]; then
          git add api.php
          git commit -m "Style: Correction automatique du code PHP"
        fi

    - name: Exécuter les tests PHPUnit
      run: |
        mkdir -p build/logs
        phpunit --log-junit build/logs/junit.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=votre-organization
          -Dsonar.projectKey=votre-project-key
          -Dsonar.php.coverage.reportPaths=build/logs/junit.xml
          -Dsonar.sources=.
          -Dsonar.test.exclusions=tests/**
          -Dsonar.tests=tests/